### ISSUE TITLE
scroll off and left margin

### ISSUE THREAD

**Issue by ghost** [honza/writer.vim#4]
Love the plugin, 

I added myself the `set foldcolumn=9` and the `set scrolloff=999` to have a left margin so the text is not too crammed on the left side, and the the second is to have the cursor always on the middle line (you might need to skip enough line at first to get the idea) 

thanks for the plugin! Will post more if I add more to it!

**Comment by honza** [comment]
Thanks, glad you like it!

**Comment by honza** [comment]
Thanks, glad you like it!
